#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/bash /etc/iftop/logger.sh
    procd_set_param respawn
    procd_close_instance
}
